const curatedCatalogItems = [
    {
        name: 'Identity Verification API',
        slug: 'identity-verification-api',
        type: 'api',
        language: 'REST',
        version: 'v1.9.0',
        description: 'KYC-grade identity checks with document validation, face match scoring, and onboarding risk signals.',
        documentation: '/docs.html#identity-verification-api',
        features: ['Document OCR', 'Face match scoring', 'Regional fraud checks'],
        icon: '</>',
        badge: 'featured',
        billingModel: 'subscription',
        allowOneTimePurchase: false,
        allowMonthlySubscription: true,
        allowYearlySubscription: true,
        oneTimePrice: 0,
        monthlyPrice: 79,
        yearlyPrice: 790,
        downloads: 12600,
        rating: 4.9,
        reviews: 184,
        isPublished: true,
        status: 'stable'
    },
    {
        name: 'Places & Geocoding API',
        slug: 'places-geocoding-api',
        type: 'api',
        language: 'REST',
        version: 'v2.4.1',
        description: 'Fast geocoding, reverse lookup, and address autocomplete tuned for logistics, travel, and checkout flows.',
        documentation: '/docs.html#places-geocoding-api',
        features: ['Forward geocoding', 'Reverse geocoding', 'Address autocomplete'],
        icon: '</>',
        badge: 'bestseller',
        billingModel: 'subscription',
        allowOneTimePurchase: false,
        allowMonthlySubscription: true,
        allowYearlySubscription: true,
        oneTimePrice: 0,
        monthlyPrice: 49,
        yearlyPrice: 490,
        downloads: 21800,
        rating: 4.8,
        reviews: 267,
        isPublished: true,
        status: 'stable'
    },
    {
        name: 'Invoice OCR API',
        slug: 'invoice-ocr-api',
        type: 'api',
        language: 'REST',
        version: 'v1.6.3',
        description: 'Extract totals, taxes, vendors, and line items from invoices and receipts with high-accuracy parsing.',
        documentation: '/docs.html#invoice-ocr-api',
        features: ['Line-item extraction', 'Multi-currency totals', 'Vendor normalization'],
        icon: '</>',
        badge: 'new',
        billingModel: 'subscription',
        allowOneTimePurchase: false,
        allowMonthlySubscription: true,
        allowYearlySubscription: true,
        oneTimePrice: 0,
        monthlyPrice: 89,
        yearlyPrice: 890,
        downloads: 9700,
        rating: 4.9,
        reviews: 143,
        isPublished: true,
        status: 'stable'
    },
    {
        name: 'Schema Guard API',
        slug: 'schema-guard-api',
        type: 'api',
        language: 'REST',
        version: 'v1.3.2',
        description: 'Deployable request validation and schema enforcement for internal APIs, partner integrations, and webhook consumers.',
        documentation: '/docs.html#schema-guard-api',
        features: ['JSON schema rules', 'Payload policy engine', 'Signed webhook validation'],
        icon: '</>',
        badge: 'featured',
        billingModel: 'one_time',
        allowOneTimePurchase: true,
        allowMonthlySubscription: false,
        allowYearlySubscription: false,
        oneTimePrice: 249,
        monthlyPrice: 0,
        yearlyPrice: 0,
        downloads: 6400,
        rating: 4.7,
        reviews: 88,
        isPublished: true,
        status: 'stable'
    },
    {
        name: 'Next.js Auth SDK',
        slug: 'nextjs-auth-sdk',
        type: 'sdk',
        language: 'Next.js',
        version: 'v2.3.0',
        description: 'Production-ready auth helpers, protected routes, and session utilities tailored for modern Next.js apps.',
        documentation: '/sdks.html#nextjs-auth-sdk',
        features: ['Route guards', 'Session hooks', 'Passwordless starter flows'],
        icon: '{ }',
        badge: 'bestseller',
        billingModel: 'one_time',
        allowOneTimePurchase: true,
        allowMonthlySubscription: false,
        allowYearlySubscription: false,
        oneTimePrice: 129,
        monthlyPrice: 0,
        yearlyPrice: 0,
        downloads: 19300,
        rating: 4.9,
        reviews: 241,
        isPublished: true,
        status: 'stable'
    },
    {
        name: 'React Native Payments SDK',
        slug: 'react-native-payments-sdk',
        type: 'sdk',
        language: 'React Native',
        version: 'v1.8.2',
        description: 'Native checkout surfaces, tokenization helpers, and mobile payment events for React Native commerce apps.',
        documentation: '/sdks.html#react-native-payments-sdk',
        features: ['Native checkout UI', 'Saved payment methods', 'Purchase event tracking'],
        icon: '{ }',
        badge: 'featured',
        billingModel: 'one_time',
        allowOneTimePurchase: true,
        allowMonthlySubscription: false,
        allowYearlySubscription: false,
        oneTimePrice: 179,
        monthlyPrice: 0,
        yearlyPrice: 0,
        downloads: 11200,
        rating: 4.8,
        reviews: 134,
        isPublished: true,
        status: 'stable'
    },
    {
        name: 'Release Channels SDK',
        slug: 'release-channels-sdk',
        type: 'sdk',
        language: 'JavaScript',
        version: 'v1.5.1',
        description: 'Managed feature rollout, staged releases, and environment-aware config delivery for web and mobile teams.',
        documentation: '/sdks.html#release-channels-sdk',
        features: ['Feature flag client', 'Release channels', 'Rollback controls'],
        icon: '{ }',
        badge: 'new',
        billingModel: 'subscription',
        allowOneTimePurchase: false,
        allowMonthlySubscription: true,
        allowYearlySubscription: true,
        oneTimePrice: 0,
        monthlyPrice: 29,
        yearlyPrice: 290,
        downloads: 8300,
        rating: 4.8,
        reviews: 97,
        isPublished: true,
        status: 'stable'
    },
    {
        name: 'Python Automation SDK',
        slug: 'python-automation-sdk',
        type: 'sdk',
        language: 'Python',
        version: 'v2.1.4',
        description: 'Typed clients, job helpers, and workflow primitives for backend automation, data operations, and scripting.',
        documentation: '/sdks.html#python-automation-sdk',
        features: ['Typed API clients', 'Workflow helpers', 'CLI automation tools'],
        icon: '{ }',
        badge: '',
        billingModel: 'one_time',
        allowOneTimePurchase: true,
        allowMonthlySubscription: false,
        allowYearlySubscription: false,
        oneTimePrice: 149,
        monthlyPrice: 0,
        yearlyPrice: 0,
        downloads: 10400,
        rating: 4.8,
        reviews: 126,
        isPublished: true,
        status: 'stable'
    }
];

const legacyCatalogSlugs = ['users-api', 'nodejs-sdk', 'python-sdk', 'data-api'];
const legacyCatalogKeywords = ['test', 'demo', 'sample', 'placeholder', 'mock', 'temp'];
const curatedCatalogSlugs = curatedCatalogItems.map((item) => item.slug);

function isLegacyTestCatalogItem(item) {
    const slug = String(item.slug || '').toLowerCase();
    const name = String(item.name || '').toLowerCase();

    if (curatedCatalogSlugs.includes(slug)) {
        return false;
    }

    if (legacyCatalogSlugs.includes(slug)) {
        return true;
    }

    return legacyCatalogKeywords.some((keyword) => slug.includes(keyword) || name.includes(keyword));
}

module.exports = {
    curatedCatalogItems,
    curatedCatalogSlugs,
    legacyCatalogSlugs,
    isLegacyTestCatalogItem
};
